export const WALKING_PROXIMITY_RADIUS_METERS = 75;
export const WALKING_EXIT_RADIUS_METERS = 120;
export const CYCLING_PROXIMITY_RADIUS_METERS = 150;
export const CYCLING_EXIT_RADIUS_METERS = 240;
export const SHOW_PULSE_ANIMATION_INSTEAD_OF_AUDIO_AUTOPLAY = true;
